### PR TITLE
improvements

### PR DESCRIPTION
**Pull request by catalint**
added dotReplacer option
upgraded to hapi 13
updated mocha package
updated mocha-lcov-reporter package

### CODE REVIEW

**Comment by mac-** [comment]
Thanks for the PR! Would you mind making sure that the indentation style stays consistent with the rest of the module? After that's fixed I'll gladly pull this in.

**Comment by catalint** [comment]
aligned code & plugin style to what hapi authors recommend , also simplified travis ci & tests

ran tests and all failed on hapi<11 , so minimum version is 11

https://github.com/hapijs/contrib/blob/master/Tests.md & https://github.com/hapijs/contrib/blob/master/Style.md 

see travis logs for details , all eslint rules are now respected

please add covverage to 100% for all tests to be successful 
```Coverage: 93.75% (3/48)
lib/hapi-statsd.js missing coverage on line(s): 17, 38, 39```

**Comment by catalint** [comment]
bump @mac-

**Comment by catalint** [comment]
bump @mac-

**Comment by catalint** [comment]
@mac- should I try and fix this conflict that is now with master? or is this PR never going to be merged?

**Pull request closed without merging**
