### PR TITLE
Version 18 and use @hapi/* namespace

### PR DESCRIPTION
**Pull request by cristobal**
* Use `@hapi/hoek` from `lib/hapi-statsd.js`
* Set peerDependency to `@hapi/hapi: ^18.0.0`

### CODE REVIEW

**Comment by zedd45** [comment]
Will this be merged? This looks like a cool library, but it doesn't seem to be maintained, anymore?

**Comment by cristobal** [comment]
> Will this be merged? This looks like a cool library, but it doesn't seem to be maintained, anymore?

Doesn’t seem so this PR is about 10 months old 😔
Never got any reply from the maintainer here...

**Comment by mac-** [comment]
Sorry for the lack of maintenance here. I've updated everything to Hapi v20 now.

**Comment by cristobal** [comment]
Np better late than never ✌️

i know how doing some open source stuff to solve own problems, suddenly gets used by many and then you end up doing maintenance and really have no time or perhaps interest because you are not using the same package anymore. 

Either way thank you for your work 🙂👍

**Pull request closed without merging**
